#!/usr/bin/env node
// Build the ShadowBase engine bundle from the website's TypeScript source.
//
// The Foundry system never re-implements a rule: every calculation, catalog,
// migration and roll-outcome table is the website's own code, bundled here by
// esbuild into one ES module that module/shadowbase.mjs imports. Rebuild this
// after the website changes (after its `npm run sync:handbook` and a green
// `node scripts/check-all.mjs`), then `npm run build:packs`.
//
//   node tools/build-engine.mjs            # writes engine/shadowbase-engine.mjs
//   SHADOWBASE_WEBSITE=<path> ...          # website checkout somewhere else
//   node tools/build-engine.mjs --minify   # smaller bundle for release
//
// The website's React, react-hook-form, Firebase and Next imports are aliased to
// the stubs in tools/stubs/. The allowed-package gate below fails the build if
// the entry ever drags in a UI or persistence package, which is the shape of the
// mistake this file exists to catch: a bundle that "works" because a stub
// silently swallowed a call.

import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { basename, dirname, join, relative, resolve, sep } from 'node:path';
import { existsSync, mkdirSync, statSync, writeFileSync, readFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { WEB } from './website-path.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const OUT_DIR = resolve(process.env.ENGINE_OUT_DIR ?? join(ROOT, 'engine'));
const OUT = join(OUT_DIR, 'shadowbase-engine.mjs');
const ENTRY = resolve(process.env.ENGINE_ENTRY ?? join(HERE, 'engine-entry.ts'));
const MINIFY = process.argv.includes('--minify');

/** Packages the bundle may contain besides the website's own src/. */
const ALLOWED_PACKAGES = new Set(['zod', 'clsx', 'tailwind-merge']);

if (!existsSync(join(WEB, 'package.json'))) {
  console.error(`build-engine: website not found at ${WEB} (set SHADOWBASE_WEBSITE)`);
  process.exit(1);
}
if (!existsSync(join(WEB, 'node_modules', 'zod'))) {
  console.error(`build-engine: the website has no node_modules (run npm ci there first)`);
  process.exit(1);
}

const require = createRequire(join(ROOT, 'package.json'));
const { build } = require('esbuild');
const stub = (name) => join(HERE, 'stubs', name);

const t0 = Date.now();
const result = await build({
  entryPoints: [ENTRY],
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2022',
  outfile: OUT,
  absWorkingDir: WEB,
  tsconfigRaw: {
    compilerOptions: {
      baseUrl: WEB,
      paths: { '@/*': ['./src/*'] },
      jsx: 'react-jsx',
      experimentalDecorators: true,
      useDefineForClassFields: false,
    },
  },
  alias: {
    'react': stub('react.js'),
    'react-dom': stub('react.js'),
    'react/jsx-runtime': stub('react.js'),
    'react/jsx-dev-runtime': stub('react.js'),
    'react-hook-form': stub('react-hook-form.js'),
    'firebase/firestore': stub('firebase.js'),
    'firebase/app': stub('firebase.js'),
    'firebase/auth': stub('firebase.js'),
    'firebase/database': stub('firebase.js'),
    'next/navigation': stub('next.js'),
    'next/link': stub('next.js'),
    'next/image': stub('next.js'),
    'next/script': stub('next.js'),
    '@/lib/handbook-loader': join(HERE, 'shims', 'handbook-loader.ts'),
  },
  logLevel: 'warning',
  metafile: true,
  minify: MINIFY,
  sourcemap: false,
  legalComments: 'none',
  banner: {
    js: [
      '// ShadowBase engine bundle - GENERATED by tools/build-engine.mjs from the ShadowBase website. Do not edit.',
      '// Rules, catalogs, migrations and roll outcomes are the website\'s own code; change them there and rebuild.',
    ].join('\n'),
  },
});

const inputs = Object.keys(result.metafile.inputs);
const packages = new Set();
for (const p of inputs) {
  if (!p.includes('node_modules/')) continue;
  const rest = p.split('node_modules/').pop();
  packages.add(rest.startsWith('@') ? rest.split('/').slice(0, 2).join('/') : rest.split('/')[0]);
}
const disallowed = [...packages].filter((p) => !ALLOWED_PACKAGES.has(p));
if (disallowed.length) {
  console.error(`build-engine: bundle pulled in packages outside the allow-list: ${disallowed.join(', ')}`);
  console.error('  The entry is importing UI or persistence code. Fix tools/engine-entry.ts.');
  process.exit(1);
}

let websiteCommit = null;
try { websiteCommit = execSync('git rev-parse --short HEAD', { cwd: WEB, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim(); } catch { /* not a repo or no git */ }
let websiteDirty = null;
try { websiteDirty = execSync('git status --porcelain', { cwd: WEB, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim().length > 0; } catch { /* ignore */ }
// BUILD-INFO is tracked, so it names the website by its repository (the remote URL, which with websiteCommit
// pins the source exactly) and the entry by its path in THIS repository - never a machine's absolute paths.
let websiteRepo = null;
try { websiteRepo = execSync('git remote get-url origin', { cwd: WEB, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim() || null; } catch { /* not a repo */ }

mkdirSync(OUT_DIR, { recursive: true });
const info = {
  generatedAt: new Date().toISOString(),
  website: websiteRepo ?? basename(WEB),
  websiteCommit,
  websiteDirty,
  esbuild: require('esbuild/package.json').version,
  bytes: statSync(OUT).size,
  minified: MINIFY,
  inputFiles: inputs.length,
  websiteSourceFiles: inputs.filter((p) => p.startsWith('src/')).length,
  packages: [...packages].sort(),
  warnings: result.warnings.length,
  entry: relative(ROOT, ENTRY).split(sep).join('/'),
  entryExports: (() => {
    try {
      const src = readFileSync(ENTRY, 'utf8');
      return (src.match(/^export /gm) ?? []).length;
    } catch { return null; }
  })(),
};
writeFileSync(join(OUT_DIR, 'BUILD-INFO.json'), JSON.stringify(info, null, 2) + '\n');

console.log(`build-engine: ${info.bytes} bytes, ${info.websiteSourceFiles} website files + ${[...packages].join(', ')} in ${Date.now() - t0} ms`);
console.log(`build-engine: website ${websiteCommit ?? '(no git)'}${websiteDirty ? ' (dirty working tree)' : ''} -> ${OUT}`);
if (result.warnings.length) console.log(`build-engine: ${result.warnings.length} esbuild warnings`);
